"""Compile the SO-101 MJCF and its STL meshes into Studio's model assets.

    python scripts/build_so101_model.py <phi checkout>/simulation/model

Writes src/phi_studio/assets/so101/model.json (the kinematic tree, joint ranges, materials and a
mesh
index) and meshes.bin (every mesh, vertices deduplicated and quantised to uint16 inside its bounding
box,
triangles as uint16 indices). The 3D view and the server's forward kinematics both read model.json,
so
the picture and the numbers come from one tree.

WHY quantise: 13 binary STLs are 18 MB; the bundle is about 3 MB. uint16 inside a mesh's own box
keeps
every vertex within 3 micrometres of the CAD (the largest part is 0.15 m across). Normals are
computed
here too, split along hard edges (creased_normals), so the browser only uploads buffers.

The MJCF is TheRobotStudio's so101_new_calib model, generated by onshape-to-robot from the SO-ARM100
CAD
(Apache 2.0). "new_calib": each joint's zero is the middle of its range, as LeRobot >= 0.5
calibrates, so
LeRobot degrees map to model radians directly; the gripper's 0..100 maps to its -10..100 degree
range.
"""

from __future__ import annotations

import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parents[1] / "src" / "phi_studio" / "assets" / "so101"
JOINTS = ["shoulder_pan", "shoulder_lift", "elbow_flex", "wrist_flex", "wrist_roll", "gripper"]


def floats(s: str | None, n: int, default: list[float]) -> list[float]:
    if s is None:
        return list(default)
    v = [float(x) for x in s.split()]
    assert len(v) == n, (s, n)
    return v


CREASE_DEG = 36.0  # faces meeting at a sharper angle keep a hard edge; gentler curves are smoothed


def creased_normals(
    verts: np.ndarray, faces: np.ndarray, crease_deg: float = CREASE_DEG
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Split vertices along hard edges and give every vertex a smooth normal over the faces it
    shares
    within the crease angle (what three.js toCreasedNormals does in the browser, done here once).

    Returns (positions [V', 3], int8 normals [V', 3], faces [T, 3] into the new vertices). WHY at
    build time:
    in the browser this took seconds of main-thread work on every page load (322k triangles)."""
    p0, p1, p2 = verts[faces[:, 0]], verts[faces[:, 1]], verts[faces[:, 2]]
    fn = np.cross(p1 - p0, p2 - p0).astype(
        np.float64
    )  # length = 2 x area: area-weighted when summed
    norm = np.linalg.norm(fn, axis=1, keepdims=True)
    fu = np.divide(fn, norm, out=np.zeros_like(fn), where=norm > 0)
    cos_t = np.cos(np.deg2rad(crease_deg))
    cv = faces.ravel()  # vertex of each corner
    cf = np.repeat(np.arange(len(faces)), 3)  # face of each corner
    order = np.argsort(cv, kind="stable")
    _, start, count = np.unique(cv[order], return_index=True, return_counts=True)
    corner_n = np.zeros((len(cv), 3))
    for k in np.unique(count):  # batch every vertex with k incident corners together
        sel = np.flatnonzero(count == k)
        idx = order[start[sel][:, None] + np.arange(k)[None, :]]  # [m, k] corner ids
        u = fu[cf[idx]]  # [m, k, 3]
        w = fn[cf[idx]]
        close = np.einsum("mid,mjd->mij", u, u) >= cos_t  # [m, k, k]
        corner_n[idx] = np.einsum("mij,mjd->mid", close.astype(np.float64), w)
    ln = np.linalg.norm(corner_n, axis=1, keepdims=True)
    corner_n = np.divide(corner_n, ln, out=np.zeros_like(corner_n), where=ln > 0)
    qn = np.clip(np.round(corner_n * 127), -127, 127).astype(np.int8)
    key = np.concatenate([cv[:, None].astype(np.int64), qn.astype(np.int64)], axis=1)
    uniq, inv = np.unique(key, axis=0, return_inverse=True)
    return verts[uniq[:, 0]], uniq[:, 1:].astype(np.int8), inv.reshape(-1, 3)


def read_stl(path: Path) -> tuple[np.ndarray, np.ndarray]:
    """Binary STL -> (unique vertices float32 [V,3], triangle indices int64 [T,3])."""
    raw = path.read_bytes()
    n = int.from_bytes(raw[80:84], "little")
    assert len(raw) == 84 + 50 * n, f"{path.name}: not a binary STL"
    rec = np.dtype([("normal", "<f4", 3), ("v", "<f4", (3, 3)), ("attr", "<u2")])
    tris = np.frombuffer(raw, dtype=rec, count=n, offset=84)["v"].reshape(-1, 3)
    verts, inv = np.unique(tris, axis=0, return_inverse=True)
    return verts.astype(np.float32), inv.reshape(-1, 3)


def body(el: ET.Element) -> dict:
    out: dict = {
        "name": el.get("name"),
        "pos": floats(el.get("pos"), 3, [0, 0, 0]),
        "quat": floats(el.get("quat"), 4, [1, 0, 0, 0]),  # MuJoCo order: w x y z
        "joint": None,
        "geoms": [],
        "sites": [],
        "children": [],
    }
    joints = el.findall("joint")
    assert len(joints) <= 1, f"body {out['name']} has {len(joints)} joints"
    if joints:
        j = joints[0]
        assert j.get("type", "hinge") == "hinge", j.attrib
        out["joint"] = {
            "name": j.get("name"),
            "axis": floats(j.get("axis"), 3, [0, 0, 1]),
            "pos": floats(j.get("pos"), 3, [0, 0, 0]),
            "range": floats(j.get("range"), 2, [0, 0]),
        }
    for g in el.findall("geom"):
        if g.get("class") != "visual":  # collision geoms repeat the visual mesh
            continue
        out["geoms"].append(
            {
                "mesh": g.get("mesh"),
                "pos": floats(g.get("pos"), 3, [0, 0, 0]),
                "quat": floats(g.get("quat"), 4, [1, 0, 0, 0]),
                "material": g.get("material"),
            }
        )
    for s in el.findall("site"):
        out["sites"].append(
            {
                "name": s.get("name"),
                "pos": floats(s.get("pos"), 3, [0, 0, 0]),
                "quat": floats(s.get("quat"), 4, [1, 0, 0, 0]),
            }
        )
    out["children"] = [body(c) for c in el.findall("body")]
    return out


def main(model_dir: str) -> None:
    src = Path(model_dir)
    xml = src / "so101_new_calib.xml"
    root = ET.parse(xml).getroot()
    assert root.find("compiler").get("angle") == "radian"
    meshdir = src / root.find("compiler").get("meshdir", "")
    tree = body(root.find("worldbody").find("body"))

    found: list[str] = []

    def walk(b: dict) -> None:
        if b["joint"]:
            found.append(b["joint"]["name"])
        for c in b["children"]:
            walk(c)

    walk(tree)
    assert found == JOINTS, found

    materials = {
        m.get("name"): floats(m.get("rgba"), 4, [1, 1, 1, 1])
        for m in root.find("asset").findall("material")
    }
    blob = bytearray()
    meshes = {}
    for m in root.find("asset").findall("mesh"):
        name = m.get("name") or Path(m.get("file")).stem
        assert m.get("scale") is None, "scaled meshes are not handled"
        verts0, faces0 = read_stl(meshdir / m.get("file"))
        verts, normals, faces = creased_normals(verts0, faces0)
        wide = len(verts) >= 65536
        lo, hi = verts.min(0), verts.max(0)
        q = np.round((verts - lo) / np.maximum(hi - lo, 1e-9) * 65535).astype("<u2")
        err = np.abs(lo + q.astype(np.float64) / 65535 * (hi - lo) - verts).max()
        assert err < 5e-6, f"{name}: quantisation error {err}"
        v_off = len(blob)
        blob += q.tobytes()
        blob += b"\0" * (-len(blob) % 4)
        n_off = len(blob)
        blob += normals.tobytes()
        blob += b"\0" * (-len(blob) % 4)
        i_off = len(blob)
        blob += faces.astype("<u4" if wide else "<u2").tobytes()
        blob += b"\0" * (-len(blob) % 4)
        meshes[name] = {
            "v": [v_off, int(len(verts))],
            "n": [n_off, int(len(verts))],
            "i": [i_off, int(faces.size)],
            "i32": wide,
            "min": [float(x) for x in lo],
            "max": [float(x) for x in hi],
        }
        print(
            f"  {name:36s} {len(verts0):6d} -> {len(verts):6d} verts {len(faces):6d} tris"
            f"  max err {err * 1e6:.2f} um"
        )

    OUT.mkdir(parents=True, exist_ok=True)
    model = {
        "name": root.get("model"),
        "source": "TheRobotStudio SO-ARM100, Simulation/SO101/so101_new_calib.xml (Apache-2.0), "
        "generated by onshape-to-robot",
        "units": {"length": "m", "angle": "rad"},
        "joints": JOINTS,
        # LeRobot reports the gripper as 0..100; the model's gripper joint spans these degrees.
        "gripper_deg": [-10.0, 100.0],
        "tcp_site": "gripperframe",
        "materials": materials,
        "meshes": meshes,
        "tree": tree,
    }
    (OUT / "model.json").write_text(json.dumps(model, separators=(",", ":")))
    (OUT / "meshes.bin").write_bytes(bytes(blob))
    print(f"wrote {OUT / 'model.json'} and meshes.bin ({len(blob) / 1e6:.2f} MB)")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    main(sys.argv[1])
